### PR TITLE
Dispose() objects correctly once we are done with them

### PR DESCRIPTION
**Pull request by MisterZeus**
Hi Erik!

3 functional changes in this one:

- added calls to objects' Dispose() methods to release their memory
- added a few more checks for the boolean _runIsCancelled, as I was hitting null reference errors when testing the Go button followed by the Cancel button. The Cancel button is still not bulletproof, but the extra checks make it less likely to error as more threads are used.
- added a CheckForOverflowUnderflow to the Debug config

And a few cosmetic ones:

- changed a few "var" to the explicit type
- renamed a badly named parameter from "E" to "Exception"
- swapped 3 instances of "---" to use the existing global var Dashes = "---"

During testing, I also happened across a case where
the while loop that kills threads gets stuck in an infinite loop,
but I have no idea how to approach fixing it.
I added a comment just before the loop (Ctrl + F for ThreadAbortException)

### CODE REVIEW

**Comment by ErikEJ** [comment]
I appreciate your contributions, but please seperate functional and cosmetic changes in seperate pull requests

**Comment by ErikEJ** [comment]
Instead of calling Dispose, use the "using" statement.

**Comment by ErikEJ** [comment]
I prefer var

**Comment by MisterZeus** [comment]
OK, shall I close this PR and split it into 2 (functional and cosmetic),
or do you prefer 1 PR per logical change?

I'll revert to var and the using statement for either of the above options.

**Comment by ErikEJ** [comment]
2 PRs would be great

**Pull request closed without merging**
