### PR TITLE
Make selfcontained

### PR DESCRIPTION
**Pull request by buckleyGI**
Hi Erik,

Can you create a selfcontained executable with this PR?

image

Is there some kind of continuous deployment in this project that I can integrate with?
Or do we create the executable manually and upload it as a git release?

The exec is zipped up so is an acceptable 69,3 Mb

### CODE REVIEW

**Comment by ErikEJ** [comment]
I will do this in the build pipeline, thanks for doing the validation

**Comment by ErikEJ** [comment]
@buckleyGI I did this instead: https://github.com/ErikEJ/SqlQueryStress/commit/e1254616b7fdcd292256aeea6a20301643513ad8

**Comment by ErikEJ** [comment]
@buckleyGI I have just updated the GitHub release with a self contained .exe, would be grateful if you could try it out.

**Comment by buckleyGI** [comment]
Sure, happy to help out
I was expecting the release on the following location or by clicking through.
Were can I find the test release? I waited a bit thinking it is a caching issue but it is not showing up.
image

**Comment by ErikEJ** [comment]
Just open the release and download the Net6 zip file

**Comment by buckleyGI** [comment]
Ha, so I had to ignore the outdated timestamp.

Download the Net6 zip file and it works as expected. Looks good.

**Pull request closed without merging**
