### PR TITLE
Add performance Gannt ,  extended event reader and form.

### PR DESCRIPTION
**Pull request by daveTechLed**

### CODE REVIEW

**Comment by ErikEJ** [comment]
@daveTechLed This PR seems to have a lot of unused and commented out code, and contains changes unrelated to the chart (async).

I cannot review the PR in its current state

**Comment by daveTechLed** [comment]
Is the async stuff a deal breaker ?  IMHO it simplifies the codebase no end and ok there is an edge case on large columns, but any performance issues will be revealed by the waits it itself shows (getting very meta now :) )

**Comment by ErikEJ** [comment]
I am not a big fan of mixing to many changes in a single PR, and as discussed, see not advantage of the async at the moment. (Might change opinion if SqlClient is "fixed")

**Comment by ErikEJ** [comment]
Why was sqlstresscmd removed from the solution?

**Comment by daveTechLed** [comment]
> I am not a big fan of mixing to many changes in a single PR, and as discussed, see not advantage of the async at the moment. (Might change opinion if SqlClient is "fixed")

Oh i agree, it is big at the moment,  let me see what i can do on the threading model.

**Comment by daveTechLed** [comment]
> Why was sqlstresscmd removed from the solution?

Yeah,  it was breaking due to dependancy on the Gantt chart, which obviously should not be there.   Will refactor  that when i get the chance.

**Comment by mdnMachine** [comment]
It would be my preference to have one ticket and only changes related to that ticket should be in the pull request. If there are x changes/improvements to be made, x PRs are easier to follow/verify. Just my two cents.

**Pull request closed without merging**
