### PR TITLE
Clean code

### PR DESCRIPTION
**Pull request by fredatgithub**
Add localhost and default server name and clean progress bar if cancelled and rename label name with numbers

### CODE REVIEW

**Comment by ErikEJ** [comment]
Thanks and lot for your effort, but this PR fixes too many issues in a single PR, and contains code reformatting on top. 

Please create small individual PRs that adresses the actual issuse, so we can discuss each 

(Add localhost and default server name and clean progress bar if cancelled and rename label name with numbers)

**Comment by fredatgithub** [comment]
ok it was my first PR so I didn't know, I'll make simpler ones.

**Comment by ErikEJ** [comment]
I appreciate your effort- always a good idea to create issues and have discussions before submitting PRs.

**Comment by fredatgithub** [comment]
ok thanks

**Pull request closed without merging**
