### PR TITLE
Label123

### PR DESCRIPTION
**Pull request by fredatgithub**
I rename controls with correct name instead of 1 2 3

### CODE REVIEW

**Comment by ErikEJ** [comment]
Too many file changes, impossible to review.

**Comment by fredatgithub** [comment]
the method private void InitializeComponent() has a lot of lines but the changes are just tabulations
the other changes are small

**Comment by ErikEJ** [comment]
Why the tabulation changes?  What editor are you using?

**Comment by fredatgithub** [comment]
I am using Visual Studio 2022 professional

**Comment by fredatgithub** [comment]
I will make another PR

**Pull request closed without merging**
