### PR TITLE
Crash fix, add UI framerate limiter during tests, fix warnings

### PR DESCRIPTION
**Pull request by MisterZeus**
Hi Erik!
I noticed a bug where the app would crash if I clicked on the Clean Buffers or Free Cache buttons while not connected to the database.
Also thought I'd try out turning on Microsoft's Visual Studio warnings to see what cropped up,, hence all the small edits to remove redundant "this" keywords, to add Dispose() calls where needed, and to capitalise the first letter of some function names.
I also added a framerate limiter to the UI Update function, since when testing with many threads, there might be loads finishing within each second, which clogs the CPU and stops the app UI from refreshing anyway.

The solution still builds fine and I did some testing of it by running some Stress scripts on a local database.

Let me know what you think!

Thanks,
Orestes

### CODE REVIEW

**Comment by MisterZeus** [comment]
hmm, I'll have a closer look at the appveyor failed build tomorrow night... :-/

**Comment by ErikEJ** [comment]
I would very much prefer a PR that focuses only on fixing the bug in question. 
Have a look at https://tirania.org/blog/archive/2010/Dec-31.html

**Comment by MisterZeus** [comment]
That is a really good article!
My apologies for the mess of a PR that I sent over, I'm quite new to this open source helping out!
I'll close this PR and try to send a simple-to-review fix for the crash bug only!

**Comment by ErikEJ** [comment]
@MisterZeus Thanks, looking forward to your PR

**Pull request closed without merging**
