### PR TITLE
FxCopAnalyzers changes

### PR DESCRIPTION
**Pull request by mertyeter**

### CODE REVIEW

**Comment by ErikEJ** [comment]
I am reluctant to take this. It would probably be better to replace the Command line parser with the nuget package instead.

**Comment by ErikEJ** [comment]
I only included the source when it was possible to distribute a single . exe, which is not the case any longer anyway.

**Comment by mertyeter** [comment]
> 
> 
> I only included the source when it was possible to distribute a single . exe, which is not the case any longer anyway.

It can be done with "dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true" command, but the file size might be huge. I'll have a look at dotnet warp utility to make it smaller as described here https://www.hanselman.com/blog/MakingATinyNETCore30EntirelySelfcontainedSingleExecutable.aspx

**Comment by ErikEJ** [comment]
There are too many changes in this PR. Please push small, reviewable PRs:

1: replace CommandLineparser
2: FxCop refactorings

No need for single .exe at the moment.

**Comment by mertyeter** [comment]
Closed for new clean PRs as FxCop refactorings contain CommandLineParser code

**Comment by ErikEJ** [comment]
Thanks, really appreciate your effort, but hope you understand the reasoning?

**Comment by ErikEJ** [comment]
Maybe just use an older version for now?

**Comment by mertyeter** [comment]
> 
> 
> Maybe just use an older version for now?

As 1.9x version is too old, has no support for .NET Core/Std. I want to implement the latest version if you don't mind :)

**Comment by ErikEJ** [comment]
I see - sure.

**Pull request closed without merging**
