### PR TITLE
Threading Model Reinstated

### PR DESCRIPTION
**Pull request by daveTechLed**

### CODE REVIEW

**Comment by daveTechLed** [comment]
Threading model redone - Seems to be "Slower" in terms of the gaps in the gannt are visibily larger and more spread out,  thoughts ??

**Comment by daveTechLed** [comment]
Have tried under "release" and things seem better,  so i'm good to push ahead with this PR if you are.  Sorry for the size, but shall we have a chat to talk the changes through ?

**Comment by daveTechLed** [comment]
Refactorings undone, any changes are now required for the gannt

**Comment by daveTechLed** [comment]
> What changed in Options.cs and some of the other files? Line endings? Spaces and tabs? It would be great if only your changes showed. If the files didn't change substantively, changes could be undone to make the pull request smaller/easier to understand. Hope this makes sense.

Nothing,  moved it to a Forms folder

**Comment by ErikEJ** [comment]
Please do any refactoring in seperate PRs, thanks.

**Pull request closed without merging**
