### PR TITLE
Rename controls to explicit name

### PR DESCRIPTION
**Pull request by fredatgithub**
I have renamed controls instead of label1, label2, etc.

### CODE REVIEW

**Comment by ErikEJ** [comment]
And it does not build...

**Comment by fredatgithub** [comment]
I have fixed the two labels which stop compilation

**Comment by fredatgithub** [comment]
in this file:
src/SQLQueryStress/DatabaseSelect.Designer.cs
there are a lot of changes but it is just tabulation

**Comment by ErikEJ** [comment]
>> src/SQLQueryStress/DatabaseSelect.Designer.cs there are a lot of changes but it is just tabulation

In that case you should be able to revert them?

But I see many files like that - 11 files changed.

**Comment by fredatgithub** [comment]
I have just reverted my changes but still 11 changes

**Comment by fredatgithub** [comment]
Let's close this PR and start over

**Pull request closed without merging**
